/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package main;

import java.awt.BasicStroke;
import java.awt.Color;
import java.awt.Graphics;
import java.awt.Graphics2D;
import java.awt.Point;
import java.awt.Stroke;
import static java.lang.Integer.parseInt;
import javafx.scene.shape.Line;
import javax.swing.JPanel;
import logica.Punt;
import logica.Vierkant;
import org.omg.CORBA.DynAnyPackage.Invalid;

/**
 *
 * @author Ruben
 */
public class Afstand_Tussen_2_Figuren extends javax.swing.JFrame {

    /**
     * Creates new form Afstand_Tussen_2_Figuren
     */
    private Color kleur;
    private Color kleur2;

    private Color kleur3;
    private Color kleur4;

    public Punt p1;
    public Punt p2;

    public Point midden1;
    public Point midden2;

    public Afstand_Tussen_2_Figuren() {
        initComponents();

        jPanel1.setBackground(groteAsPanel1.getBackground()); //middenV
        jPanel4.setBackground(groteAsPanel1.getBackground()); //randV
        newJPanel2.setBackground(groteAsPanel1.getBackground()); //punt
        newJPanel2.setVisible(false); //punt

        jPanel5.setBackground(groteAsPanel1.getBackground()); //middenV
        jPanel6.setBackground(groteAsPanel1.getBackground()); //randV
        newJPanel6.setBackground(groteAsPanel1.getBackground()); //punt
        newJPanel6.setVisible(false); //punt

        newJPanel3.setVisible(false); //rand
        newJPanel4.setVisible(false); //midden
        newJPanel5.setVisible(false); //punt

        newJPanel7.setVisible(false); //rand
        newJPanel8.setVisible(false); //midden
        newJPanel9.setVisible(false); //punt

        newJPanel3.setBackground(new Color(0, 0, 0, 0)); //transparant maken
        newJPanel4.setBackground(new Color(0, 0, 0, 0));
        newJPanel5.setBackground(new Color(0, 0, 0, 0));
        newJPanel7.setBackground(new Color(0, 0, 0, 0)); //transparant maken
        newJPanel8.setBackground(new Color(0, 0, 0, 0));
        newJPanel9.setBackground(new Color(0, 0, 0, 0));

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jTextField1 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        jComboBox1 = new javax.swing.JComboBox<>();
        jTextField3 = new javax.swing.JTextField();
        jComboBox2 = new javax.swing.JComboBox<>();
        jComboBox3 = new javax.swing.JComboBox<>();
        jSpinner1 = new javax.swing.JSpinner();
        jPanel3 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jTextField4 = new javax.swing.JTextField();
        jTextField5 = new javax.swing.JTextField();
        jComboBox4 = new javax.swing.JComboBox<>();
        jTextField6 = new javax.swing.JTextField();
        jComboBox5 = new javax.swing.JComboBox<>();
        jComboBox6 = new javax.swing.JComboBox<>();
        jSpinner2 = new javax.swing.JSpinner();
        groteAsPanel1 = new main.GroteAsPanel();
        jPanel4 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        newJPanel2 = new main.NewJPanel();
        newJPanel3 = new main.NewJPanel();
        newJPanel4 = new main.NewJPanel();
        newJPanel5 = new main.NewJPanel();
        jPanel5 = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        newJPanel6 = new main.NewJPanel();
        newJPanel7 = new main.NewJPanel();
        newJPanel8 = new main.NewJPanel();
        newJPanel9 = new main.NewJPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextArea2 = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel1.setText("Middelpunt Xcoordinaat");

        jLabel2.setText("Middelpunt Ycoordinaat");

        jLabel3.setText("Type Figuur");

        jLabel4.setText("Grootte Figuur");

        jLabel5.setText("Kleur figuur");

        jLabel6.setText("Kleur rand");

        jLabel7.setText("Dikte Rand");

        jButton1.setText("Verwerk");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Vierkant", "Cirkel" }));

        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "zwart", "wit", "rood", "oranje","geel" }));

        jComboBox3.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "zwart", "wit", "rood", "oranje","geel" }));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5)
                            .addComponent(jLabel6)
                            .addComponent(jLabel7)
                            .addComponent(jLabel1))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 26, Short.MAX_VALUE)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jTextField2)
                                .addComponent(jComboBox1, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jTextField3, javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jComboBox2, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jComboBox3, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jSpinner1, javax.swing.GroupLayout.DEFAULT_SIZE, 101, Short.MAX_VALUE)))
                        .addGap(46, 46, 46))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(10, 10, 10)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(8, 8, 8)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(19, 19, 19)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(jComboBox3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(jSpinner1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel8.setText("Middelpunt Xcoordinaat");

        jLabel9.setText("Middelpunt Ycoordinaat");

        jLabel10.setText("Type Figuur");

        jLabel11.setText("Grootte Figuur");

        jLabel12.setText("Kleur figuur");

        jLabel13.setText("Kleur rand");

        jLabel14.setText("Dikte Rand");

        jButton2.setText("Verwerk");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jComboBox4.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Vierkant", "Cirkel" }));

        jComboBox5.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "zwart", "wit", "rood", "oranje","geel" }));

        jComboBox6.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "zwart", "wit", "rood", "oranje","geel" }));

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel9)
                            .addComponent(jLabel10)
                            .addComponent(jLabel11)
                            .addComponent(jLabel12)
                            .addComponent(jLabel13)
                            .addComponent(jLabel14)
                            .addComponent(jLabel8))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 20, Short.MAX_VALUE)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jTextField5)
                                .addComponent(jComboBox4, 0, 101, Short.MAX_VALUE)
                                .addComponent(jTextField6, javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jComboBox5, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jComboBox6, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jSpinner2)))
                        .addGap(46, 46, 46))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(jTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(10, 10, 10)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel9)
                    .addComponent(jTextField6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel10)
                    .addComponent(jComboBox4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(8, 8, 8)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(jTextField5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(19, 19, 19)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(jComboBox5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13)
                    .addComponent(jComboBox6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel14)
                    .addComponent(jSpinner2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton2)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel4.setBackground(new java.awt.Color(51, 255, 0));

        jPanel1.setBackground(new java.awt.Color(255, 102, 153));

        javax.swing.GroupLayout newJPanel2Layout = new javax.swing.GroupLayout(newJPanel2);
        newJPanel2.setLayout(newJPanel2Layout);
        newJPanel2Layout.setHorizontalGroup(
            newJPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 30, Short.MAX_VALUE)
        );
        newJPanel2Layout.setVerticalGroup(
            newJPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 30, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(newJPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(8, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(newJPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(15, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(21, Short.MAX_VALUE))
        );

        newJPanel3.setBackground(new java.awt.Color(204, 255, 102));
        newJPanel3.setForeground(new java.awt.Color(255, 0, 0));

        newJPanel4.setBackground(new java.awt.Color(255, 153, 153));

        newJPanel5.setBackground(new java.awt.Color(255, 102, 102));

        javax.swing.GroupLayout newJPanel5Layout = new javax.swing.GroupLayout(newJPanel5);
        newJPanel5.setLayout(newJPanel5Layout);
        newJPanel5Layout.setHorizontalGroup(
            newJPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 30, Short.MAX_VALUE)
        );
        newJPanel5Layout.setVerticalGroup(
            newJPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 28, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout newJPanel4Layout = new javax.swing.GroupLayout(newJPanel4);
        newJPanel4.setLayout(newJPanel4Layout);
        newJPanel4Layout.setHorizontalGroup(
            newJPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, newJPanel4Layout.createSequentialGroup()
                .addContainerGap(23, Short.MAX_VALUE)
                .addComponent(newJPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(22, 22, 22))
        );
        newJPanel4Layout.setVerticalGroup(
            newJPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(newJPanel4Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(newJPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(21, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout newJPanel3Layout = new javax.swing.GroupLayout(newJPanel3);
        newJPanel3.setLayout(newJPanel3Layout);
        newJPanel3Layout.setHorizontalGroup(
            newJPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, newJPanel3Layout.createSequentialGroup()
                .addContainerGap(27, Short.MAX_VALUE)
                .addComponent(newJPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(24, 24, 24))
        );
        newJPanel3Layout.setVerticalGroup(
            newJPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(newJPanel3Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(newJPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(25, Short.MAX_VALUE))
        );

        jPanel5.setBackground(new java.awt.Color(51, 255, 0));

        jPanel6.setBackground(new java.awt.Color(255, 102, 153));

        javax.swing.GroupLayout newJPanel6Layout = new javax.swing.GroupLayout(newJPanel6);
        newJPanel6.setLayout(newJPanel6Layout);
        newJPanel6Layout.setHorizontalGroup(
            newJPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 30, Short.MAX_VALUE)
        );
        newJPanel6Layout.setVerticalGroup(
            newJPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 30, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(newJPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(17, Short.MAX_VALUE))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                .addContainerGap(21, Short.MAX_VALUE)
                .addComponent(newJPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(14, 14, 14))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(18, 18, 18))
        );

        newJPanel7.setBackground(new java.awt.Color(204, 255, 102));
        newJPanel7.setForeground(new java.awt.Color(255, 0, 0));

        newJPanel8.setBackground(new java.awt.Color(255, 153, 153));

        newJPanel9.setBackground(new java.awt.Color(255, 102, 102));

        javax.swing.GroupLayout newJPanel9Layout = new javax.swing.GroupLayout(newJPanel9);
        newJPanel9.setLayout(newJPanel9Layout);
        newJPanel9Layout.setHorizontalGroup(
            newJPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 30, Short.MAX_VALUE)
        );
        newJPanel9Layout.setVerticalGroup(
            newJPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 28, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout newJPanel8Layout = new javax.swing.GroupLayout(newJPanel8);
        newJPanel8.setLayout(newJPanel8Layout);
        newJPanel8Layout.setHorizontalGroup(
            newJPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, newJPanel8Layout.createSequentialGroup()
                .addContainerGap(24, Short.MAX_VALUE)
                .addComponent(newJPanel9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(21, 21, 21))
        );
        newJPanel8Layout.setVerticalGroup(
            newJPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, newJPanel8Layout.createSequentialGroup()
                .addContainerGap(23, Short.MAX_VALUE)
                .addComponent(newJPanel9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18))
        );

        javax.swing.GroupLayout newJPanel7Layout = new javax.swing.GroupLayout(newJPanel7);
        newJPanel7.setLayout(newJPanel7Layout);
        newJPanel7Layout.setHorizontalGroup(
            newJPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, newJPanel7Layout.createSequentialGroup()
                .addContainerGap(27, Short.MAX_VALUE)
                .addComponent(newJPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(24, 24, 24))
        );
        newJPanel7Layout.setVerticalGroup(
            newJPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(newJPanel7Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(newJPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(25, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout groteAsPanel1Layout = new javax.swing.GroupLayout(groteAsPanel1);
        groteAsPanel1.setLayout(groteAsPanel1Layout);
        groteAsPanel1Layout.setHorizontalGroup(
            groteAsPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, groteAsPanel1Layout.createSequentialGroup()
                .addGap(79, 79, 79)
                .addComponent(newJPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(33, 33, 33)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 186, Short.MAX_VALUE)
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(77, 77, 77)
                .addComponent(newJPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(111, 111, 111))
        );
        groteAsPanel1Layout.setVerticalGroup(
            groteAsPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(groteAsPanel1Layout.createSequentialGroup()
                .addGroup(groteAsPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(groteAsPanel1Layout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addComponent(newJPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(groteAsPanel1Layout.createSequentialGroup()
                        .addGap(38, 38, 38)
                        .addComponent(newJPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(groteAsPanel1Layout.createSequentialGroup()
                        .addGap(46, 46, 46)
                        .addGroup(groteAsPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(204, Short.MAX_VALUE))
        );

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        jTextArea2.setColumns(20);
        jTextArea2.setRows(5);
        jScrollPane2.setViewportView(jTextArea2);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(31, 31, 31)
                        .addComponent(groteAsPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(74, 74, 74)
                                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(103, 103, 103)
                                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(23, 23, 23)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(42, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 41, Short.MAX_VALUE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addGap(28, 28, 28)
                .addComponent(groteAsPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(41, 41, 41))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        //LINKS
        newJPanel2.setVisible(true); //punt
        System.err.println(jPanel1.getLocation());
        System.err.println(jPanel4.getLocation());
        String figuur1 = jComboBox1.getSelectedItem() + "";
        try {
            int MiddelX1 = parseInt(jTextField1.getText());
            int MiddelY1 = parseInt(jTextField3.getText());
            int grootte1 = parseInt(jTextField2.getText());
            int dikteRand1 = (Integer) jSpinner1.getValue();

            if (figuur1.equals("Vierkant")) {
                setKleuren();
                setVierkantStatus1(true);
                setCirlelStatus1(false);

                Vierkant v = new Vierkant(grootte1);
                jPanel1.setSize(grootte1, grootte1); //MIDDEN
                jPanel4.setSize(grootte1 + dikteRand1, grootte1 + dikteRand1); //RAND

                jPanel4.setLocation(MiddelX1, MiddelY1); //rand
                jPanel1.setBackground(kleur);
                jPanel4.setBackground(kleur2); //rand
                newJPanel2.setBackground(jPanel1.getBackground()); //punt
                setMidden(jPanel1);//RAND
                setMidden(newJPanel2);//punt

                double x = newJPanel2.getLocationOnScreen().getX();
                double y = newJPanel2.getLocationOnScreen().getY();

                midden1 = new Point((int) x, (int) y);

            } else if (figuur1.equals("Cirkel")) {
                setKleuren();
                setCirlelStatus1(true);
                setVierkantStatus1(false);

                newJPanel3.setLocation(MiddelX1, MiddelY1); //rand
                newJPanel4.setSize(grootte1, grootte1); //MIDDEN
                newJPanel3.setSize(grootte1 + dikteRand1, grootte1 + dikteRand1); //RAND
                System.err.println("size of rand " + newJPanel3.getSize());
                System.err.println("size of inner " + newJPanel4.getSize());
                setMidden(newJPanel4);//midden
                setMidden(newJPanel5);//punt
                newJPanel4.setKleur(kleur);//midden
                newJPanel3.setKleur(kleur2); //rand

                double x = newJPanel5.getLocationOnScreen().getX();
                double y = newJPanel5.getLocationOnScreen().getY();
                midden1 = new Point((int) x, (int) y);
            }
        } catch (Exception e) {

            System.err.println("Alles moet ingevuld worden");
        }

        //     p1 = getLinksPunt(figuur1);

    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:

        String figuur1 = jComboBox4.getSelectedItem() + "";

        try {

            int MiddelX1 = parseInt(jTextField4.getText());
            int MiddelY1 = parseInt(jTextField6.getText());
            int grootte1 = parseInt(jTextField5.getText());
            int dikteRand1 = (Integer) jSpinner2.getValue();

            if (figuur1.equals("Vierkant")) {
                setKleuren2();
                setVierkantStatus2(true);
                setCirlelStatus2(false);

                Vierkant v = new Vierkant(grootte1);
                jPanel6.setSize(grootte1, grootte1); //MIDDEN
                jPanel5.setSize(grootte1 + dikteRand1, grootte1 + dikteRand1); //RAND

                jPanel6.setLocation(MiddelX1, MiddelY1); //rand
                jPanel5.setBackground(kleur3);
                jPanel6.setBackground(kleur4); //rand
                newJPanel6.setBackground(jPanel5.getBackground()); //punt
                setMidden(jPanel6);//RAND
                setMidden(newJPanel6);//punt
                newJPanel9.setBackground(new Color(0, 0, 0, 0));

                double x = newJPanel6.getLocationOnScreen().getX();
                double y = newJPanel6.getLocationOnScreen().getY();
                midden2 = new Point((int) x, (int) y);

            } else if (figuur1.equals("Cirkel")) {

                setCirlelStatus2(true);
                setVierkantStatus2(false);
                setKleuren2();
                newJPanel7.setLocation(MiddelX1, MiddelY1); //rand
                setMidden(newJPanel8);//midden
                setMidden(newJPanel9);//punt
                newJPanel8.setKleur(kleur3);//midden
                newJPanel7.setKleur(kleur4); //rand
                double x = newJPanel9.getLocationOnScreen().getX();
                double y = newJPanel9.getLocationOnScreen().getY();
                midden2 = new Point((int) x, (int) y);

            }
        } catch (Exception e) {

            System.err.println("Alles moet ingevuld worden");
        }
        //   p2 = getRechtsPunt(figuur1);
//        double afstand = p1.berekenAfstand(p2);
        //  jTextArea2.setText("afstand :" + afstand);
        //  System.err.println("afstand :" + afstand);
        /*
        Punt p1 = new Punt(newJPanel6.getX(), newJPanel6.getY());
        Punt p2 = new Punt(newJPanel2.getX(), newJPanel2.getY());
        double afstand = p1.berekenAfstand(p2);
        System.err.println("afstand :" + afstand);
        jTextArea2.setText("afstand :" + afstand);
         */
        Graphics g = this.getGraphics();

        drawDashedLine(g, (int) midden1.getX() -400, (int) midden1.getY(), (int) midden2.getX() -400, (int) midden2.getY());

        System.out.println("line coords : " + (int) midden1.getX() + " " + (int) midden1.getY() + " " + (int) midden2.getX() + " " + (int) midden2.getY());
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;

                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Afstand_Tussen_2_Figuren.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Afstand_Tussen_2_Figuren.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Afstand_Tussen_2_Figuren.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Afstand_Tussen_2_Figuren.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Afstand_Tussen_2_Figuren().setVisible(true);
            }
        });
    }

    public void setVierkantStatus1(boolean b) {

        System.err.println("vierkantstatus is " + b);

        jPanel1.setEnabled(b); //rand
        jPanel4.setEnabled(b); //midden
        newJPanel2.setEnabled(b); //punt

        jPanel1.setVisible(b); //rand
        jPanel4.setVisible(b); //midden
        newJPanel2.setVisible(b); //punt

    }

    public void setVierkantStatus2(boolean b) {

        System.err.println("vierkantstatus is " + b);

        jPanel5.setEnabled(b); //rand
        jPanel6.setEnabled(b); //midden
        newJPanel6.setEnabled(b); //punt

        jPanel5.setVisible(b); //rand
        jPanel6.setVisible(b); //midden
        newJPanel6.setVisible(b); //punt

    }

    public void setCirlelStatus1(boolean b) {

        System.err.println("cirkelstatus is " + b);
        newJPanel3.setEnabled(b); //rand
        newJPanel4.setEnabled(b); //midden
        newJPanel5.setEnabled(b); //punt

        newJPanel3.setVisible(b); //rand
        newJPanel4.setVisible(b); //midden
        newJPanel5.setVisible(b); //punt

    }

    public void setCirlelStatus2(boolean b) {

        System.err.println("cirkelstatus is " + b);
        newJPanel7.setEnabled(b); //rand
        newJPanel8.setEnabled(b); //midden
        newJPanel9.setEnabled(b); //punt

        newJPanel7.setVisible(b); //rand
        newJPanel8.setVisible(b); //midden
        newJPanel9.setVisible(b); //punt

    }

    public Punt getLinksPunt(String figuur) {
        double x = 0;
        double y = 0;
        Punt p;

        if (figuur.equals("Vierkant")) {

            x = newJPanel2.getLocationOnScreen().getX();
            y = newJPanel2.getLocationOnScreen().getY();

            midden1 = new Point((int) x, (int) y);

        } else if (figuur.equals("Cirkel")) {

            x = newJPanel5.getLocationOnScreen().getX();
            y = newJPanel5.getLocationOnScreen().getY();
            midden1 = new Point((int) x, (int) y);
        }

        return new Punt((int) x, (int) y);

    }

    public Punt getRechtsPunt(String figuur) {
        double x = 0;
        double y = 0;
        Punt p;
        if (figuur.equals("Vierkant")) {

            x = newJPanel6.getLocationOnScreen().getX();
            y = newJPanel6.getLocationOnScreen().getY();
            midden2 = new Point((int) x, (int) y);
        } else if (figuur.equals("Cirkel")) {

            x = newJPanel9.getLocationOnScreen().getX();
            y = newJPanel9.getLocationOnScreen().getY();
            midden2 = new Point((int) x, (int) y);
        }

        return new Punt((int) x, (int) y);
    }

    public void setKleuren() {
        String color1 = jComboBox2.getSelectedItem() + "";
        String color2 = jComboBox3.getSelectedItem() + "";
        if ("zwart".equals(color1)) {
            kleur = Color.BLACK;

        } else if ("wit".equals(color1)) {
            kleur = Color.WHITE;

        } else if ("rood".equals(color1)) {
            kleur = Color.RED;

        } else if ("oranje".equals(color1)) {
            kleur = Color.ORANGE;

        } else if ("geel".equals(color1)) {
            kleur = Color.YELLOW;

        }
        if ("zwart".equals(color2)) {
            kleur2 = Color.BLACK;

        } else if ("wit".equals(color2)) {
            kleur2 = Color.WHITE;

        } else if ("rood".equals(color2)) {
            kleur2 = Color.RED;

        } else if ("oranje".equals(color2)) {
            kleur2 = Color.ORANGE;

        } else if ("geel".equals(color2)) {
            kleur2 = Color.YELLOW;

        }

    }

    public void setKleuren2() {
        String color1 = jComboBox5.getSelectedItem() + "";
        String color2 = jComboBox6.getSelectedItem() + "";
        if ("zwart".equals(color1)) {
            kleur3 = Color.BLACK;

        } else if ("wit".equals(color1)) {
            kleur3 = Color.WHITE;

        } else if ("rood".equals(color1)) {
            kleur3 = Color.RED;

        } else if ("oranje".equals(color1)) {
            kleur3 = Color.ORANGE;

        } else if ("geel".equals(color1)) {
            kleur3 = Color.YELLOW;

        }
        if ("zwart".equals(color2)) {
            kleur4 = Color.BLACK;

        } else if ("wit".equals(color2)) {
            kleur4 = Color.WHITE;

        } else if ("rood".equals(color2)) {
            kleur4 = Color.RED;

        } else if ("oranje".equals(color2)) {
            kleur4 = Color.ORANGE;

        } else if ("geel".equals(color2)) {
            kleur4 = Color.YELLOW;

        }

    }

    public void setMidden(JPanel j) {

        //dus we zetten het midden van de ene fram op het midden van de andere frame 
        int panelX = j.getParent().getWidth() / 2;

        int panelY = j.getParent().getHeight() / 2;

        int p1 = j.getWidth() / 2;
        int p2 = j.getHeight() / 2;

        j.setLocation(panelX - p1, panelY - p2);

    }

    public void drawDashedLine(Graphics g, int x1, int y1, int x2, int y2) {

        //creates a copy of the Graphics instance
        Graphics2D g2d = (Graphics2D) g.create();

        //set the stroke of the copy, not the original 
        Stroke dashed = new BasicStroke(3, BasicStroke.CAP_BUTT, BasicStroke.JOIN_BEVEL, 0, new float[]{9}, 0);
        g2d.setStroke(dashed);
        g2d.drawLine(x1, y1, x2, y2);

        //gets rid of the copy
        g2d.dispose();
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private main.GroteAsPanel groteAsPanel1;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JComboBox<String> jComboBox2;
    private javax.swing.JComboBox<String> jComboBox3;
    private javax.swing.JComboBox<String> jComboBox4;
    private javax.swing.JComboBox<String> jComboBox5;
    private javax.swing.JComboBox<String> jComboBox6;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSpinner jSpinner1;
    private javax.swing.JSpinner jSpinner2;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextArea jTextArea2;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JTextField jTextField6;
    private main.NewJPanel newJPanel2;
    private main.NewJPanel newJPanel3;
    private main.NewJPanel newJPanel4;
    private main.NewJPanel newJPanel5;
    private main.NewJPanel newJPanel6;
    private main.NewJPanel newJPanel7;
    private main.NewJPanel newJPanel8;
    private main.NewJPanel newJPanel9;
    // End of variables declaration//GEN-END:variables
}
